/**
 * Image URL helper — REAL ESTATE version.
 *
 * All images now point to local /realestate/{name}.png files — real
 * estate property photography (houses, villas, apartments, farmland,
 * pools, terraces, Miami skylines) generated by the z-ai image-
 * generation skill. See scripts/gen_realestate_images.sh for the
 * generation prompts.
 *
 * For seed names that don't have a dedicated image, we map to the
 * closest matching existing image based on context (e.g., 'amen-3'
 * (The Grotto) reuses 'expann-6' (the Grotto gallery image).
 *
 * The width/height args are kept for API compatibility with the old
 * picsum-based helper, but are ignored — the local images are served
 * at their native size and aspect-ratio boxes crop them via CSS.
 */

// Direct-mapped seeds (have a dedicated .png file in /realestate/).
const DIRECT: Record<string, string> = {
  'expann-hero':       'expann-hero',
  'expann-1':          'expann-1',
  'expann-2':          'expann-2',
  'expann-3':          'expann-3',
  'expann-4':          'expann-4',
  'expann-5':          'expann-5',
  'expann-6':          'expann-6',
  'expann-7':          'expann-7',
  'expann-wide':       'expann-wide',
  'expann-philosophy': 'expann-philosophy',
  'amen-1':            'amen-1',
}

// Reuse map: seed → existing image name (closest match by context).
const REUSE: Record<string, string> = {
  // Projects page cards — reuse the matching residence-type gallery image
  'expann-studio': 'expann-3',  // studio
  'expann-1br':    'expann-4',  // one-bedroom
  'expann-2br':    'expann-5',  // two-bedroom

  // Floor plans — show the corresponding residence interior (no actual
  // floor-plan diagram generated; reuse the interior photo as a stand-in)
  'fp-expann-studio': 'expann-3',
  'fp-expann-1br':    'expann-4',
  'fp-expann-2br':    'expann-5',

  // Amenities — 3 of 6 reuse gallery images (same physical spaces)
  'amen-2': 'expann-2',  // Gallery lobby + coffee bar = expann-2
  'amen-3': 'expann-6',  // The Grotto = expann-6
  'amen-4': 'expann-2',  // Meeting gallery = lobby (closest)
  'amen-5': 'expann-7',  // Fitness center = rooftop (natural light + view)
  'amen-6': 'expann-7',  // Rooftop = expann-7

  // Leadership cards — no corporate headshots generated; reuse the
  // lobby image (interior with human-scale space) as a stand-in.
  // The Story page leadership section was removed since real headshots
  // weren't available, so these mappings are only used if re-enabled.
  'leader-1': 'expann-2',
  'leader-2': 'expann-2',
  'leader-3': 'expann-2',
  'leader-4': 'expann-2',

  // District landscapes — Miami skyline is the closest match for all
  // 6 districts without dedicated aerial photos
  'district-expann':   'expann-wide',
  'district-design':   'expann-1',
  'district-midtown':  'expann-1',
  'district-brickell': 'expann-wide',
  'district-downtown': 'expann-wide',
  'district-beach':    'expann-7',
}

function resolve(seed: string): string {
  // Direct match wins
  if (DIRECT[seed]) return DIRECT[seed]
  // Reuse map
  if (REUSE[seed]) return REUSE[seed]
  // Fallback to the hero image for any unknown seed
  return 'expann-hero'
}

export interface ImageSpec {
  seed: string
  width: number
  height: number
}

export const portrait = (seed: string, _w = 900, _h = 1200): string =>
  `/realestate/${resolve(seed)}.png`

export const landscape = (seed: string, _w = 1920, _h = 1080): string =>
  `/realestate/${resolve(seed)}.png`

export const og = (seed: string): string =>
  `/realestate/${resolve(seed)}.png`
