/**
 * Image URL helper — REAL ESTATE version.
 *
 * All images now point to local /realestate/{name}.png files — real
 * estate property photography (houses, villas, apartments, farmland,
 * pools, terraces, Miami skylines) generated by the z-ai image-
 * generation skill. See scripts/gen_realestate_images.sh for the
 * generation prompts.
 *
 * For seed names that don't have a dedicated image, we map to the
 * closest matching existing image based on context (e.g., 'amen-3'
 * (The Grotto) reuses 'expaan-6' (the Grotto gallery image).
 *
 * The width/height args are kept for API compatibility with the old
 * picsum-based helper, but are ignored — the local images are served
 * at their native size and aspect-ratio boxes crop them via CSS.
 */

// Direct-mapped seeds (have a dedicated .png file in /realestate/).
const DIRECT: Record<string, string> = {
  'expaan-hero':       'expaan-hero',
  'expaan-1':          'expaan-1',
  'expaan-2':          'expaan-2',
  'expaan-3':          'expaan-3',
  'expaan-4':          'expaan-4',
  'expaan-5':          'expaan-5',
  'expaan-6':          'expaan-6',
  'expaan-7':          'expaan-7',
  'expaan-wide':       'expaan-wide',
  'expaan-philosophy': 'expaan-philosophy',
  'amen-1':            'amen-1',
}

// Reuse map: seed → existing image name (closest match by context).
const REUSE: Record<string, string> = {
  // Projects page cards — reuse the matching residence-type gallery image
  'expaan-studio': 'expaan-3',  // studio
  'expaan-1br':    'expaan-4',  // one-bedroom
  'expaan-2br':    'expaan-5',  // two-bedroom

  // Floor plans — show the corresponding residence interior (no actual
  // floor-plan diagram generated; reuse the interior photo as a stand-in)
  'fp-expaan-studio': 'expaan-3',
  'fp-expaan-1br':    'expaan-4',
  'fp-expaan-2br':    'expaan-5',

  // Amenities — 3 of 6 reuse gallery images (same physical spaces)
  'amen-2': 'expaan-2',  // Gallery lobby + coffee bar = expaan-2
  'amen-3': 'expaan-6',  // The Grotto = expaan-6
  'amen-4': 'expaan-2',  // Meeting gallery = lobby (closest)
  'amen-5': 'expaan-7',  // Fitness center = rooftop (natural light + view)
  'amen-6': 'expaan-7',  // Rooftop = expaan-7

  // Leadership cards — no corporate headshots generated; reuse the
  // lobby image (interior with human-scale space) as a stand-in.
  // The Story page leadership section was removed since real headshots
  // weren't available, so these mappings are only used if re-enabled.
  'leader-1': 'expaan-2',
  'leader-2': 'expaan-2',
  'leader-3': 'expaan-2',
  'leader-4': 'expaan-2',

  // District landscapes — Miami skyline is the closest match for all
  // 6 districts without dedicated aerial photos
  'district-expaan':   'expaan-wide',
  'district-design':   'expaan-1',
  'district-midtown':  'expaan-1',
  'district-brickell': 'expaan-wide',
  'district-downtown': 'expaan-wide',
  'district-beach':    'expaan-7',
}

function resolve(seed: string): string {
  // Direct match wins
  if (DIRECT[seed]) return DIRECT[seed]
  // Reuse map
  if (REUSE[seed]) return REUSE[seed]
  // Fallback to the hero image for any unknown seed
  return 'expaan-hero'
}

export interface ImageSpec {
  seed: string
  width: number
  height: number
}

export const portrait = (seed: string, _w = 900, _h = 1200): string =>
  `/realestate/${resolve(seed)}.png`

export const landscape = (seed: string, _w = 1920, _h = 1080): string =>
  `/realestate/${resolve(seed)}.png`

export const og = (seed: string): string =>
  `/realestate/${resolve(seed)}.png`
